### ISSUE TITLE
Strange error when running on PE 3.8

### ISSUE THREAD

**Issue by Jmeyering** [saz/puppet-ssh#134] opened 2015-07-08 15:47 UTC
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, uncaught throw :undefined_variable in thread 0x213a2 at /etc/puppetlabs/puppet/modules/ssh/manifests/hostkeys.pp:2:18 on node
```

Any thoughts on this?

**Comment by thomasbergmann** [comment] 2015-11-17 16:07
Same error on Puppet 4.2.

**Comment by thomasbergmann** [comment] 2015-11-17 16:23
It´s the ipaddresses function at lib/puppet/parser/functions/ipaddresses.rb causing this error.

**Comment by joshuaspence** [comment] 2016-01-31 09:22
I am also hitting this error, on puppet 4

**Comment by petems** [comment] 2016-05-13 19:31
It's caused by `strict_variables=true`, I think the lookups need to be re-written to not get nil lookups...

**Comment by saz** [comment] 2016-08-26 16:04
This should be fixed in the current master

**Closed by saz** 2016-08-26 16:04 UTC
