### ISSUE TITLE
Warning: You cannot collect exported resources without storeconfigs being set

### ISSUE THREAD

**Issue by siebrand** [saz/puppet-ssh#340] opened 2022-11-14 13:54 UTC
I'm seeing this output in puppetserver.log with module version 10.0.0:

```
2022-11-14T15:50:51.706+02:00 WARN  [qtp578288908-126] [puppetserver] Puppet You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /etc/puppetlabs/code/environments/production/modules/ssh/manifests/hostkeys.pp, line: 68, column: 7)
2022-11-14T15:50:51.708+02:00 WARN  [qtp578288908-126] [puppetserver] Puppet You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /etc/puppetlabs/code/environments/production/modules/ssh/manifests/hostkeys.pp, line: 61, column: 7)
2022-11-14T15:50:51.709+02:00 WARN  [qtp578288908-126] [puppetserver] Puppet You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /etc/puppetlabs/code/environments/production/modules/ssh/manifests/hostkeys.pp, line: 61, column: 7)
2022-11-14T15:50:51.711+02:00 WARN  [qtp578288908-126] [puppetserver] Puppet You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /etc/puppetlabs/code/environments/production/modules/ssh/manifests/hostkeys.pp, line: 61, column: 7)
2022-11-14T15:50:51.721+02:00 WARN  [qtp578288908-126] [puppetserver] Puppet You cannot collect exported resources without storeconfigs being set; the collection will be ignored (file: /etc/puppetlabs/code/environments/production/modules/ssh/manifests/knownhosts.pp, line: 18, column: 7)
```

I just updated from module version 8.0.0. That had the same 5 warnings, just on different line numbers.

**Comment by slauger** [comment] 2022-11-17 20:44
You just have to enable the storeconfigs feature on your puppetserver. This is not a bug related to the module.

**Comment by deric** [comment] 2023-02-16 11:51
See [Puppet server](https://www.puppet.com/docs/puppet/7/config_important_settings.html#settings_for_puppet_primary_servers-server-extensions) documentation, basically you need to have a PuppetDB instance (or something that implements the interface).

If you don't want to use this feature, disable `storeconfigs_enabled`:
```yaml
ssh::storeconfigs_enabled: false
```

**Comment by saz** [comment] 2023-02-16 12:20
Yep. As this is not related to this module, I'll close the issue

**Closed by saz** 2023-02-16 12:20 UTC
