### ISSUE TITLE
Puppet 4 Errors

### ISSUE THREAD

**Issue by Jmeyering** [saz/puppet-ssh#137] opened 2015-07-14 05:09 UTC
Receiving custom fact errors on puppet 4

```
Error: Facter: error while resolving custom fact "ssh_client_version_full": undefined method `lines' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_client_version_major": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_client_version_release": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_full": undefined method `lines' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_major": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_release": undefined method `gsub' for nil:NilClass
```

**Comment by erude1** [comment] 2015-07-23 18:02
I think this is fixed as of version 3.0.2 of Facter. I was seeing the same behavior, but after updating my puppet client the custom facts appear to be working now.

I suspect the following is the change that fixed the issue.
https://tickets.puppetlabs.com/browse/FACT-1115

**Comment by gotyaoi** [comment] 2015-07-23 18:54
I can confirm this is fixed in facter 3.0.2.

Before 3.0.2 dropped, as a workaround, I edited the facts in question, changing
`Facter::Util::Resolution.exec('sshd -V 2>&1')`
to
`Facter::Util::Resolution.exec('sshd -V 2>&1 || true')`
which seemed to make facter happy.

**Comment by Jmeyering** [comment] 2015-07-24 01:37
Confirmed fixed :+1:

**Closed** 2015-07-24 01:37 UTC

**Comment by joshuaspence** [comment] 2015-09-14 10:35
Hmm, this doesn't seem to be fixed for me.

```
> /opt/puppetlabs/puppet/bin/ruby -rfacter -e 'puts Facter.version'
3.0.2

> /opt/puppetlabs/puppet/bin/ruby -rfacter -e 'puts Facter::Core::Execution.exec("sshd -V 2>&1").inspect'
nil

> /opt/puppetlabs/puppet/bin/ruby -rfacter -e 'puts Facter::Util::Resolution.exec("sshd -V 2>&1").inspect'
nil
```

**Comment by vladgh** [comment] 2015-10-18 13:51
I get the same error on Ubuntu Trusty, unless `openssh-server` is installed.

What doesn't really make sense is why both `ssh_client_version.rb` and `ssh_server_version.rb` run the same command `sshd -V`, which is the executable provided by the OpenSSH Server package (not to mention it's also wrong, because there is no such command line option for the server, as stated in the comment).

In my opinion, both client and server facts should only query the version number from the client (`ssh -V`), because this is provided by the openssh-server anyway (at least on Ubuntu).

But what really brought me here is that they should also fail silently in the eventuality that no ssh/sshd is installed on the server.

**Comment by vladgh** [comment] 2015-10-18 14:38
Sorry, I just saw that my comment was a duplicate of #140

**Comment by pjmorr** [comment] 2016-01-08 13:11
I am seeing this issue now but only on all of my windows machines...

**Comment by jessereynolds** [comment] 2016-03-02 23:18
I'm seeing this error on Windows hosts with the latest Puppet Enterprise agent (2015.3.2) installed:

PS C:\Users\Administrator> facter --version
3.1.4 (commit c08a5ed7606b6cd8be3a146b247c03bf7213c445)
PS C:\Users\Administrator> puppet --version
4.3.2
                 
The errors show up in all puppet agent runs on windows when the saz/ssh module is installed on the puppet master. 

For now I have removed saz/ssh from the puppet master. :-(

**Comment by jessereynolds** [comment] 2016-03-02 23:26
Created #171 to track this special case.

**Comment by wazoo** [comment] 2016-03-16 22:53
I also ran into this as I was using the forge version, have updated to git and issue went away.  As others have said this becomes an issue because every time puppet runs it puts 6 errors in the windows event logs and that throws off monitoring.  Do you have an ETA on when the forge version will be updated?

**Comment by jrwesolo** [comment] 2016-06-23 20:38
I'd also love this to get released to the Forge. I'm getting the same errors only on Windows hosts.
