### ISSUE TITLE
v2.8.1 causes puppet to throw errors on windows hosts

### ISSUE THREAD

**Issue by jessereynolds** [saz/puppet-ssh#171] opened 2016-03-02 23:25 UTC
I'm seeing the following errors on Windows hosts with the latest Puppet Enterprise agent (2015.3.2) installed, and when saz/ssh 2.8.1 (latest on the forge) is installed on the puppet master:

```
Error: Facter: error while resolving custom fact "ssh_client_version_full": undefined method `lines' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_client_version_major": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_client_version_release": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_full": undefined method `lines' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_major": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_release": undefined method `gsub' for nil:NilClass
```

PS C:\Users\Administrator> facter --version
3.1.4 (commit c08a5ed7606b6cd8be3a146b247c03bf7213c445)
PS C:\Users\Administrator> puppet --version
4.3.2

The errors show up in all puppet agent runs on windows when the saz/ssh module is installed on the puppet master.

**Comment by rbramwell** [comment] 2016-03-10 02:52
Came across this issue today, went to fix it and submit a PR but then saw that master/trunk already had the resolution to this: placing confines in the custom facts to include all supported kernels, which excludes windows. Don't know when a new release will be made but would be nice to have the updated code on the forge to prevent this issue in mixed (with windows) environments.

**Comment by jrwesolo** [comment] 2016-06-23 20:38
I'd love a release of this to the Forge as well.

**Comment by dannygoulder** [comment] 2016-06-24 18:49
I would also appreciate if this could be released. Pretty please!!!

**Comment by jrwesolo** [comment] 2016-06-24 18:53
If anyone is using r10k, I am using this in my Puppetfile to pull in the fix:

```
mod 'saz/ssh',
  git: 'https://github.com/saz/puppet-ssh.git',
  ref: 'd0c77c06b7d9e03c9c30f564605e07535ee8f5c9'
```

Once we get a new release, I switch it back to using the forge version.

**Comment by jrwesolo** [comment] 2016-07-18 23:29
@saz any updates on this?

**Comment by senax** [comment] 2016-08-05 08:59
A new release on the forge would be much appreciated. I'm sure that many companies block cloning from github but allow forge downloads. An update would be much appreciated.

Unfortunately puppet pushes out all ${module_name}/lib/facter/ to all nodes, even when the module is not assigned to it :/

**Comment by saz** [comment] 2016-08-21 14:57
I'm in the process of preparing a new release asap. I hope to get it released until the end of next week

**Comment by saz** [comment] 2016-08-26 09:01
I'll close this issue, as it is resolved in the current master and will be published soon.

**Comment by devoncustard** [comment] 2016-08-29 16:31
not sure this is fixed. I pulled the current master and im still getting the same error. 

I believe the issue is with the version = .... statement being outside the setcode do block. 

Soon as i moved that line.... well im happier now ;)

**Comment by saz** [comment] 2016-08-30 12:35
@devoncustard Can you provide a diff of your changes please?

**Comment by saz** [comment] 2016-08-30 13:44
This should be fixed now. I've also added tests for the facts.

**Closed by saz** 2016-08-30 13:44 UTC

**Comment by devoncustard** [comment] 2016-08-30 18:08
ah you beat me to it. looking forward to seeing this on the forge but for now I can link my r10k to here.

**Comment by saz** [comment] 2016-08-30 18:11
Just have a look at the new release on the forge ;-)
